export * from './Home/Home'
export * from './About/About'
export * from './Catalog/Catalog'
export * from './NotFound/NotFound'
export * from './Product/Product'
export * from './Cart/Cart'
export * from './Favorites/Favorites'
